### ISSUE TITLE
Error Module browserlist

### ISSUE THREAD

**Issue by mdunisch** [postcss/autoprefixer-core#39]
Hey,

4 minutes ago I installed gulp-autoprefixer and get the deps of gulp-autoprefixer I get the latest (5.1.8) version of autoprefixer-core.

Unfortunately my gulp stop working: 

```
module.js:338
    throw err;
    ^
Error: Cannot find module 'browserslist'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/myproject/node_modules/gulp-autoprefixer/node_modules/autoprefixer-core/lib/autoprefixer.js:6:18)
    at Object.<anonymous> (/myproject//node_modules/gulp-autoprefixer/node_modules/autoprefixer-core/lib/autoprefixer.js:109:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

After I install v5.1.7 manually It works again.
I did this with:

```cli
> cd node_modules/gulp-autoprefixer
> npm install autoprefixer-core@5.1.7
```

**Comment by ai** [comment]
I right now made a simple repo with `autoprefixer` in dependencies and everything was installed.

Can you remove `node_modules` dir and reinstall npm packages again.

I think you maybe had a network error during 5.1.8 install.

**Comment by mdunisch** [comment]
Thank you. You're right - I tried again today and it works!
