### ISSUE TITLE
error when compiling mixin of polymer

### ISSUE THREAD

**Issue by oscarmarina** [postcss/autoprefixer-core#51]
https://www.polymer-project.org/0.9/docs/devguide/styling.html#custom-css-mixins
--my-toolbar-theme: {
    background-color: green;
    border-radius: 4px;
    border: 1px solid gray;
  }

[13:59:53] gulp-ruby-sass: write main.css
[13:59:53] gulp-ruby-sass: write main.css.map

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Can't parse CSS: Unexpected { at line 65:23
    at Transform.stream._transform (/Users/administrador/projects/net-09/node_modules/gulp-autoprefixer/index.js:67:30)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Transform.Writable.write (_stream_writable.js:217:11)
    at Transform.ondata (_stream_readable.js:540:20)
    at Transform.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Transform.Readable.push (_stream_readable.js:126:10)

**Comment by ai** [comment]
Does `--my-toolbar-theme:` is a correct CSS selector? PostCSS can parse only CSS.

**Comment by oscarmarina** [comment]
It is part of the w3c specification for implentación CSS variables. http://dev.w3.org/csswg/css-variables/. Currently implemented in Firefox. It has raised its support?

**Comment by ai** [comment]
@oscarmarina can you open a issue in [PostCSS](https://github.com/postcss/postcss) repo?

Autoprefixer doesn’t parse a CSS files. It is just a plugin,

**Comment by ai** [comment]
@oscarmarina BTW, I can’t find a `--my-toolbar-theme: { }` notation in that spec.

PostCSS already had a plugin to polyfill custom properties: https://github.com/postcss/postcss-custom-properties

So we can sure, that PostCSS can parse that spec. Maybe `--my-toolbar-theme: { }` is part of some spec extension?

**Comment by ai** [comment]
Very strange. PostCSS can parse this CSS: I insert this CSS in [inetractive demo](http://simevidas.jsbin.com/gufoko/quiet) and its works fine. What version of Autoprefixer do you use?
